/**
 * Script to copy Strapi types from backend to frontend
 *
 * This copies the generated type definitions from the Strapi backend
 * to the frontend for type-safe API consumption, and auto-generates
 * an index.ts file with all exports.
 *
 * Requires: @strapi/strapi installed as a dev dependency
 * Run: yarn add --dev @strapi/strapi
 *
 * Usage: node scripts/copyTypes.js
 */

const fs = require('fs');
const path = require('path');

const destinationFolder = 'src/types/generated';

const files = [
  {
    src: path.join(__dirname, '../../backend/types/generated/contentTypes.d.ts'),
    dest: path.join(__dirname, `../${destinationFolder}/contentTypes.d.ts`),
  },
  {
    src: path.join(__dirname, '../../backend/types/generated/components.d.ts'),
    dest: path.join(__dirname, `../${destinationFolder}/components.d.ts`),
  },
];

/**
 * Add header comment to the content
 */
function transformContent(content, filename) {
  const header = `/**
 * Auto-generated from Strapi backend
 * File: ${filename}
 * 
 * DO NOT EDIT - This file is synced from backend/types/generated/
 * Run 'npm run types:sync' to update
 */

`;
  return header + content;
}

/**
 * Extract exported interface names from a .d.ts file content
 */
function extractExportedInterfaces(content) {
  const regex = /export interface (\w+)/g;
  const interfaces = [];
  let match;
  while ((match = regex.exec(content)) !== null) {
    interfaces.push(match[1]);
  }
  return interfaces;
}

/**
 * Convert interface name to a friendly alias
 * e.g., ApiArticleArticle -> ArticleSchema, ElementsFeature -> FeatureSchema
 */
function toFriendlyAlias(name) {
  // Remove common prefixes
  let alias = name
    .replace(/^Api(\w+)\1$/i, '$1') // ApiArticleArticle -> Article
    .replace(/^Api/, '') // ApiGlobalGlobal -> GlobalGlobal -> handled below
    .replace(/^Elements/, '')
    .replace(/^Sections/, '')
    .replace(/^Layout/, '')
    .replace(/^Links/, '')
    .replace(/^Meta/, '')
    .replace(/^Shared/, 'Shared') // Keep Shared prefix to avoid conflicts
    .replace(/^Admin\w+$/, '') // Skip admin types
    .replace(/^Plugin\w+$/, ''); // Skip plugin types
  
  // Handle duplicated names like GlobalGlobal -> Global
  alias = alias.replace(/^(\w+)\1$/i, '$1');
  
  return alias ? `${alias}Schema` : null;
}

/**
 * Generate index.ts content
 */
function generateIndexContent(contentTypesInterfaces, componentsInterfaces) {
  // Filter to only API types (not Admin or Plugin types)
  const apiTypes = contentTypesInterfaces.filter(name => name.startsWith('Api'));
  // Filter components - exclude types that contain "ComponentSchemas" (module augmentation)
  const componentTypes = componentsInterfaces.filter(name => 
    !name.startsWith('Admin') && 
    !name.startsWith('Plugin') &&
    !name.includes('ComponentSchemas')
  );

  // Create aliases and track used names to avoid duplicates
  const usedAliases = new Set();
  
  const contentTypeAliases = apiTypes
    .map(name => ({ name, alias: toFriendlyAlias(name) }))
    .filter(item => {
      if (!item.alias || usedAliases.has(item.alias)) return false;
      usedAliases.add(item.alias);
      return true;
    });
  
  const componentAliases = componentTypes
    .map(name => ({ name, alias: toFriendlyAlias(name) }))
    .filter(item => {
      if (!item.alias || usedAliases.has(item.alias)) return false;
      usedAliases.add(item.alias);
      return true;
    });

  // Generate import statements
  const contentTypeImports = contentTypeAliases.map(({ name }) => name);
  const componentImports = componentAliases.map(({ name }) => name);

  return `/**
 * Generated Types Index
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * This file is auto-generated by scripts/copyTypes.js
 * Run 'npm run types:sync' to update
 */

// Re-export all schema types
export * from './contentTypes';
export * from './components';

// Re-export Strapi types for advanced use cases
export type { Schema, Struct } from '@strapi/strapi';

// Import types for aliases
import type {
${contentTypeImports.map(name => `  ${name},`).join('\n')}
} from './contentTypes';

import type {
${componentImports.map(name => `  ${name},`).join('\n')}
} from './components';

// =============================================================================
// UTILITY TYPES FOR STRAPI V5
// =============================================================================

/**
 * Base entity type with common Strapi fields
 */
export interface StrapiEntity {
  id: number;
  documentId: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  locale?: string;
}

/**
 * Media file type for Strapi v5
 */
export interface StrapiMediaFile {
  id: number;
  documentId: string;
  url: string;
  alternativeText: string | null;
  caption?: string | null;
  name: string;
  width?: number;
  height?: number;
  mime: string;
  formats?: {
    thumbnail?: MediaFormat;
    small?: MediaFormat;
    medium?: MediaFormat;
    large?: MediaFormat;
  };
}

interface MediaFormat {
  url: string;
  width: number;
  height: number;
  name: string;
}

// =============================================================================
// CONTENT TYPE SCHEMA ALIASES
// =============================================================================

${contentTypeAliases.map(({ name, alias }) => `export type ${alias} = ${name};`).join('\n')}

// =============================================================================
// COMPONENT SCHEMA ALIASES
// =============================================================================

${componentAliases.map(({ name, alias }) => `export type ${alias} = ${name};`).join('\n')}
`;
}

function copyFile({ src, dest }) {
  const destinationDir = path.dirname(dest);
  const filename = path.basename(src);

  if (!fs.existsSync(src)) {
    console.error(`Source file does not exist: ${src}`);
    process.exit(1);
  }

  if (!fs.existsSync(destinationDir)) {
    fs.mkdirSync(destinationDir, { recursive: true });
  }

  const content = fs.readFileSync(src, 'utf8');
  const transformedContent = transformContent(content, filename);

  fs.writeFileSync(dest, transformedContent);
  console.log(`✓ Copied: ${filename}`);
  
  return content; // Return original content for parsing
}

console.log('Copying Strapi types from backend to frontend...\n');

// Copy files and collect their content
const contentTypesContent = copyFile(files[0]);
const componentsContent = copyFile(files[1]);

// Extract interfaces
const contentTypesInterfaces = extractExportedInterfaces(contentTypesContent);
const componentsInterfaces = extractExportedInterfaces(componentsContent);

console.log(`  Found ${contentTypesInterfaces.length} content types`);
console.log(`  Found ${componentsInterfaces.length} components`);

// Generate index.ts
const indexContent = generateIndexContent(contentTypesInterfaces, componentsInterfaces);
const indexPath = path.join(__dirname, `../${destinationFolder}/index.ts`);
fs.writeFileSync(indexPath, indexContent);
console.log(`✓ Generated: index.ts`);

console.log('\nDone! Types copied to frontend/src/types/generated/');
